### ISSUE TITLE
add repository on HACS on HAOS (supervised) don't work

### ISSUE THREAD

**Issue by chris777c** [Superkikim/mh-maxsmart-hass#10]
Hello,

I try to add repository : https://github.com/Superkikim/mh-maxsmart-hass.git  on HAOS but I show me this message : 

`https://github.com/Superkikim/mh-maxsmart-hass.git is not a valide repository add-on`

my configuration :  
 Core 2024.6.3
Supervisor 2024.06.2
Operating System 12.4
Interface utilisateur 20240610.1

**Comment by Superkikim** [comment]
Hi.

Remove .git from the URL. It should work.

That said, I'm about to get back to development. Stay posted. 

I'll get to it in the coming week.

**Comment by Superkikim** [comment]
By the way, try removing .git from the linkLe 14 juil. 2024 à 08:37, chris777c ***@***.***> a écrit :﻿
Hello,
I try to add repository : https://github.com/Superkikim/mh-maxsmart-hass.git  on HAOS but I show me this message :
https://github.com/Superkikim/mh-maxsmart-hass.git is not a valide repository add-on
my configuration :
Core 2024.6.3
Supervisor 2024.06.2
Operating System 12.4
Interface utilisateur 20240610.1

**Comment by chris777c** [comment]
Hello, 

Thank you for reply but i had the same effect with this url : https://github.com/Superkikim/mh-maxsmart-hass.

Ok I wait your activity , have a good day

**Comment by Superkikim** [comment]
I'll try tonight on my test instance

**Comment by Superkikim** [comment]
> Hello, 
> 
> 
> 
> Thank you for reply but i had the same effect with this url : https://github.com/Superkikim/mh-maxsmart-hass.
> 
> 
> 
> Ok I wait your activity , have a good day

Meanwhile, you can install it manually. Download the latest beta

https://github.com/Superkikim/mh-maxsmart-hass/releases

**Comment by Superkikim** [comment]
No issues on my side to install the plugin. 

I just deployed a brand new homeassistant:stable container (2024.7.2). I was able to add my repo to HACS, however all the versions seems to be buggy now. I have to rework on this. Stay posted. I'll try to deploy a working release within 10 days.

**Comment by Superkikim** [comment]
I justed deployed a supervised version (haos) in a VM. 
I was able to install HACS, add my repo, enable beta view, download beta 3, and detect my devices. 

Not sure what your issue is, but doesn't seem to be related to the repo or the release.

**Comment by chris777c** [comment]
Hello,

What url repo have you insert on haos ?

**Comment by Superkikim** [comment]
https://github.com/Superkikim/mh-maxsmart-hass

**Comment by chris777c** [comment]
![image001](https://github.com/user-attachments/assets/9d2e6049-6923-4c5a-b7fb-26eef99b5afe)

This screenshot with error

**Comment by Superkikim** [comment]
That's weird.

My versions: 

HACS: 

> Integration version: 	1.34.0
> Frontend version: 	20220906112053
> Repositories: 	1386
> Downloaded repositories: 	2
>

HA: 

> Core 2024.7.2
> Supervisor 2024.06.2
> Operating System 12.4
> Frontend 20240710.0
> 

![image](https://github.com/user-attachments/assets/04aa16a7-28b2-4fbb-8f07-2df95b7d883a)

![image](https://github.com/user-attachments/assets/38300c26-c6d0-425f-bc3c-ace3294b73ca)
