### ISSUE TITLE
Deprecated constant used

### ISSUE THREAD

**Issue by flle** [Superkikim/mh-maxsmart-hass#12]
Hi,

as requested here https://github.com/Superkikim/maxsmart/issues/1 I am opening this issue here again.
I stumbled accross this message for the maxsmart integration in my Home Assisstant log:
DEVICE_CLASS_POWER was used from maxsmart, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead, please report it to the author of the 'maxsmart' custom integration.

Looking forward to a fix.
Thanks!

**Comment by Superkikim** [comment]
Will be fixed in next version. Tx for bringing it to my attention.
