### ISSUE TITLE
-beta in version tag violates HA versioning scheme

### ISSUE THREAD

**Issue by lmaertin** [Superkikim/mh-maxsmart-hass#2]
Component is broken due to the“-beta” in the version tag inside the manifest. May introduce patch level version numbers for betas.

Quickfix "removing -beta" resolves the issue. Testet in latest HA:
Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4

**Comment by Superkikim** [comment]
Just fixed. 2023.7.0-beta1 is working with fw 1.30 for switches and sensors. Currently working on the dev branch on 2023.8.0-beta1 to support other fw versions, but with generic names. 

Name customization will be the next step
